[theme]
primary = "default"
[ui]
# title = "blue"
# border = "gray"
highlight = "#551133"
cursor = "red"
# status = "green"
# background = "black"
[tabs]
active = { fg = "#e4e4e4", bg = "black", underline = true}
inactive = { fg = "#5555bb", bg = "black"}
sep_inner = { fg = "#e4e4e4", bg = "black", open = "|", close = "|" }
sep_outer = { fg = "#e4e4e4", bg = "black", open = " ", close = " "}

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "yellow" },

  # Videos
  { mime = "video/*", fg = "magenta" },
  { mime = "audio/*", fg = "magenta" },

  # Empty files
  { mime = "inode/empty", fg = "cyan" },

  # Orphan symbolic links
  { name = "*", is = "orphan", fg = "red" },

  # ...

  # Fallback
  # { name = "*", fg = "white" },
  { name = "*/", fg = "#FFA764" }, # directory
]
#ğŸ”¨âš™ï¸ğŸ‘»ğŸ“ ğŸ“‚ğŸ“„ğŸ“‡ğŸ“ƒğŸ“œğŸ“ğŸ”ŒğŸ«ğŸŒ„ğŸ—»ğŸ†ğŸ¦„ğŸª„ğŸ§ğŸ’«âœï¸ğŸ—ğŸªµğŸ™ğŸ”‘ğŸ’¾ğŸ™ˆğŸï¸ğŸŒğŸ’»ğŸ§‘â€ğŸ’»ï¸ğŸ§°ğŸ¬ğŸğŸ–¥
#ğŸ§ğŸ¥ğŸ¹ğŸ’ƒğŸª©ğŸ¤ï¸ğŸ«ğŸ”ŠğŸª—ğŸºğŸ§™ğŸ»ğŸ‘¨ğŸ¼â€ğŸ¨ğŸ‘¨ğŸ¾â€ğŸ’»ğŸâ˜„ï¸â˜ƒï¸ğŸŒˆğŸğŸ•¸ğŸ¦‘ğŸŒ»ğŸŒ¼ğŸŒ¸ğŸŒºğŸŒ¹ğŸ®ğŸŒŒğŸŒ‡ğŸŒğŸâš—ï¸ğŸ’ˆğŸ¦ ğŸ“‘ğŸ“¦
#ğŸ“’ğŸ“•ğŸ“—ğŸ“˜ğŸ“™ğŸ“šğŸ“–ğŸ”–ğŸğŸ“ŒğŸ“ğŸ§·ğŸ”—â›“ï¸ğŸ§±ğŸªœğŸ’¡â˜¯ï¸ğŸ”´ğŸ”‰ğŸš©ğŸğŸ´â€â˜ ï¸ğŸ©»ğŸª¸ğŸ›ŸğŸ›ğŸªªğŸ«£ğŸª½ğŸ§‘ğŸ¿â€â¤ï¸â€ğŸ’‹â€ğŸ§‘ğŸ¾â›³ğŸ‡·ğŸ‡ºğŸª†ğŸ§¸
#ğŸªğŸ£ğŸ¥¥â›½ğŸ¢ğŸšğŸ¦ªğŸŒğŸ©ğŸ§‘â€ğŸ”§ï¸ğŸ§‘â€ğŸ­ï¸ğŸ§‘â€ğŸ’»ï¸ğŸ¦ºğŸšœğŸ’¼ğŸ¼ğŸ¦†ğŸ“©ğŸ’½ğŸ®ğŸ§ğŸ›‚ğŸ“’ğŸ““ğŸ“”ğŸ“™ğŸ“‘ğŸšƒğŸšŠğŸ‘«ğŸ”‘
[icon]
append_dirs = [
  { name = ".scripts", text = "ğŸ“œ" },
  { name = ".config", text = "âš™ï¸" },
  { name = ".git", text = "î—» ", fg = "#00afff", rg = "#00afff" },
  { name = ".ssh", text = "ğŸ”‘", fg = "#00afff", rg = "#00afff" },
  { name = ".npm", text = "î—º  ", fg = "#00afff", rg = "#00afff" },
  { name = "Work", text = "ğŸ§‘â€ğŸ’»ï¸" },
  { name = "Desktop", text = "ğŸ’»" },
  { name = "Documents", text = "ğŸ“‘" },
  { name = "Public", text = "ğŸŸ ", fg = "#00afff" },
  { name = "Downloads", text = "ğŸ“©" },
  { name = "Games", text = "ğŸ®" },
  { name = "Music", text = "ğŸ§" },
  { name = "Pictures", text = "ğŸŒº" },
  { name = "Videos", text = "ğŸ¥" },
  { name = "Panda", text = "ğŸ¼" },
  { name = "Panda1", text = "ğŸ¼" },
  { name = "Panda2", text = "ğŸ¼" },
  { name = "Panda3", text = "ğŸ¼" },
]
append_exts = [
  { name = "meta", text = "ğŸ”–", fg = "#00afff" }, # Hidden directoriesğŸ§°ğŸ› ğŸ”¨
  { name = "cs", text = "ğŸ’»", fg = "#00afff" },   # Hidden directoriesğŸ§°ğŸ› ğŸ”¨
  # { name = "mp3", text = "ï€", fg = "#00afff" },
]
prepend_conds = [
  { if = "hidden & dir", text = "ğŸ’¼", fg = "#00afff" }, # Hidden directories
  { if = "link", text = "ğŸ”—", fg = "#00afff" },         # Hidden directories
  { if = "dir", text = "ï» ", fg = "#00afff" },         # Directories
  { if = "!(dir | link)", text = "ğŸ“„" },                # Normal files (not directories or smlinks)
]
